#!/bin/sh -e

# https://clang.llvm.org/docs/UsersManual.html

export CFLAGS='-Wall -O -g --coverage -fprofile-filter-files=".*\.c$\"'
export LDFLAGS='-Wall -O -g --coverage -fprofile-filter-files="ad2vcf"'
rm -f *.gcno *.gcda
make clean all
./ad2vcf Test/test.vcf < Test/test.sam
llvm-cov gcov ad2vcf.gcda
more ad2vcf.c.gcov
