ad2vcf.o: ad2vcf.c /usr/local/include/htslib/sam.h \
  /usr/local/include/htslib/hts.h /usr/local/include/htslib/hts_defs.h \
  /usr/local/include/htslib/hts_log.h \
  /usr/local/include/htslib/kstring.h \
  /usr/local/include/htslib/kroundup.h \
  /usr/local/include/htslib/hts_endian.h ../local/include/vcfio.h \
  ../local/include/dsvio.h ../local/include/samio.h \
  ../local/include/biostring.h ad2vcf.h ad2vcf-protos.h
	${CC} -c ${CFLAGS} ad2vcf.c

